#
# This source file is part of the Stanford Biodesign Digital Health Group Swift Template Package open source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Build-and-Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_tests_linux:
    name: Build and Test Swift Package Linux
    uses: StanfordBDHG/.github/.github/workflows/swift-test.yml@v2
    strategy:
      matrix:
        config: [Debug, Release]
      fail-fast: false
    with:
      build_configuration: ${{ matrix.config }}
      artifact_name: ${{ format('SpeziVapor-Package-Linux-{0}.lcov', matrix.config) }}
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [package_tests_linux]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports_lcov: SpeziVapor-Package-Linux-*.lcov
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}